# Regression - How does a school's environment affect its students' ELA Assessment scores?

Predict percentage of students who will receive 3+ on the ELA assessment

**Import Packages**

In [1]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import seaborn as sns
sns.set_style('white')
import matplotlib.pyplot as plt
%matplotlib inline

**Read Data**

In [16]:
nyc_schools_ela = pd.read_csv('Data/nyc_schools_ela.csv')
nyc_schools_ela.head()

,DBN,School Name,Supportive Environment Rating,Interesting and challenging curriculum,Effective teaching and learning,Effective school assessment,Clear communication - high expectations,Teacher collaboration,"Safety, inclusivity, social-emotional growth",Resource allocation and management,...,Strong Family-Community Ties Score,Trust Score,Borough,District,Level 1 %,Level 2 %,Level 3 %,Level 4 %,Level 3+ %,% Tested
0,01M015,P.S. 015 Roberto Clemente,4,4,3,3,3,3,4,4,...,3.80,3.99,M,1,7.462687,25.373135,46.268658,20.895523,67.164177,0.387283
1,01M019,P.S. 019 Asher Levy,3,4,4,4,4,4,4,4,...,4.10,3.55,M,1,11.956522,32.608696,39.130436,16.304348,55.434784,0.377049
2,01M020,P.S. 020 Anna Silver,2,2,2,2,3,2,3,3,...,3.64,3.12,M,1,30.143541,30.143541,28.229666,11.483253,39.712917,0.451404
3,01M034,P.S. 034 Franklin D. Roosevelt,2,2,2,2,3,3,2,3,...,3.33,2.32,M,1,33.644859,39.719627,18.224298,8.411215,26.635513,0.668750
4,01M063,The STAR Academy - P.S.63,3,4,3,4,3,4,4,4,...,4.01,3.95,M,1,6.250000,35.937500,42.187500,15.625000,57.812500,0.361582